# Generated by Django 5.0.3 on 2024-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookLover',
            fields=[
                ('id_book_lover', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'BookLover',
            },
        ),
    ]
