# Generated by Django 5.0.3 on 2024-03-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название издательства')),
            ],
            options={
                'db_table': 'Publisher',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код области')),
                ('name', models.CharField(max_length=100, verbose_name='Название области')),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.AlterField(
            model_name='booklover',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booklover',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booklover',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booklover',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booklover',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year_of_release', models.PositiveIntegerField(null=True)),
                ('cover_photo', models.ImageField(null=True, upload_to='book_covers/')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='first_lab.publisher')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='first_lab.region', verbose_name='Область'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id_volume', models.AutoField(primary_key=True, serialize=False)),
                ('volume_number', models.PositiveIntegerField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_lab.book')),
            ],
            options={
                'db_table': 'VolumeBook',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='volumes',
            field=models.ManyToManyField(null=True, related_name='volume', to='first_lab.volume'),
        ),
    ]
