# Generated by Django 5.0.3 on 2024-03-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_lab', '0002_publisher_region_alter_booklover_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='volumes',
            field=models.ManyToManyField(related_name='volume', to='first_lab.volume'),
        ),
    ]
