# Generated by Django 5.0.3 on 2024-03-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_lab', '0003_alter_book_volumes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('code', 'id')},
        ),
    ]
