# Generated by Django 5.0.3 on 2024-03-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_lab', '0004_alter_region_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewBook',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='book_covers/')),
            ],
            options={
                'db_table': 'PreviewBook',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='volumes',
            field=models.ManyToManyField(null=True, related_name='volume', to='first_lab.volume'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_book', to='first_lab.previewbook'),
        ),
    ]
