# Generated by Django 5.0.3 on 2024-03-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_lab', '0005_previewbook_alter_book_volumes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='book_covers/'),
        ),
        migrations.DeleteModel(
            name='PreviewBook',
        ),
    ]
