# Generated by Django 5.0.3 on 2024-03-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_lab', '0006_alter_book_cover_photo_delete_previewbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_lab.publisher'),
        ),
    ]
