# Generated by Django 5.0.3 on 2024-03-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_lab', '0008_alter_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='volumes',
        ),
        migrations.AlterField(
            model_name='volume',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='first_lab.book'),
        ),
    ]
